version: '3.3'

volumes:
  static_foodgram:
  media_foodgram:
  pg_data_foodgram:

services:

  db:
    platform: linux/amd64
    image: postgres:13
    env_file:
      - ./.env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data/
    

  backend:
    platform: linux/amd64
    image: waynje/foodgram_backend
    env_file:
      - ./.env
    restart: always
    volumes:
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/
    depends_on:
      - db
    
  
  frontend:
    platform: linux/amd64
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    platform: linux/amd64
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always
  

