version: '3.3'
services:

  volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data/
    env_file:
      - ./.env

   backend:
    image: waynje/foodgram_backend
    restart: always
    volumes:
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  frontend:
    build:
      image: waynje/foodgram_frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always
  
  volumes:
  static_value:
  media_value:
  db_foodgram:
