# Generated by Django 3.2 on 2023-12-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
