# Generated by Django 3.2 on 2023-12-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231228_0028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='unique_ingredients',
        ),
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredients'),
        ),
    ]
