# Generated by Django 3.2 on 2023-12-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
